// Run: node lib/transcript.test.js
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { messageFrom, followTranscript } = require('./transcript');

const entry = (o) => ({ timestamp: '2026-01-01T00:00:00Z', ...o });
const say = (type, content) => entry({ type, message: { content } });

// ── what counts as a real reply ──────────────────────────────────────────────
assert.deepStrictEqual(
  messageFrom(say('assistant', [{ type: 'text', text: 'Hello there' }])),
  { role: 'assistant', text: 'Hello there', ts: '2026-01-01T00:00:00Z' });
assert.deepStrictEqual(
  messageFrom(say('user', 'fix the bug')),
  { role: 'user', text: 'fix the bug', ts: '2026-01-01T00:00:00Z' });

// ── what is plumbing, and must never reach the phone as a message ────────────
assert.strictEqual(messageFrom(say('assistant', [{ type: 'tool_use', name: 'Read', input: {} }])), null,
  'tool calls are not replies');
assert.strictEqual(messageFrom(say('user', [{ type: 'tool_result', content: 'file contents' }])), null,
  'tool results are not replies');
assert.strictEqual(messageFrom(say('user', '<command-name>/clear</command-name>')), null);
assert.strictEqual(messageFrom(say('user', '<local-command-stdout>ok</local-command-stdout>')), null);
assert.strictEqual(messageFrom(say('user', 'Caveat: The messages below were generated by the user')), null);
assert.strictEqual(messageFrom(say('user', '[Request interrupted by user]')), null);
assert.strictEqual(messageFrom(entry({ type: 'system', message: { content: 'hook fired' } })), null);
assert.strictEqual(messageFrom(entry({ type: 'assistant', isSidechain: true, message: { content: [{ type: 'text', text: 'subagent' }] } })), null,
  'subagent turns are not this conversation');
assert.strictEqual(messageFrom(entry({ type: 'user', isMeta: true, message: { content: 'meta' } })), null);
assert.strictEqual(messageFrom(say('assistant', [{ type: 'text', text: '   ' }])), null, 'whitespace is not a reply');

// System reminders are stripped from otherwise-real user turns.
assert.strictEqual(
  messageFrom(say('user', 'do the thing<system-reminder>secret context</system-reminder>')).text,
  'do the thing');

// Mixed block: keep the prose, drop the tool call.
assert.strictEqual(
  messageFrom(say('assistant', [{ type: 'text', text: 'Reading it now.' }, { type: 'tool_use', name: 'Read' }])).text,
  'Reading it now.');

// ── tailing: only new lines, partial writes held until complete ──────────────
const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'clim-')), 's.jsonl');
fs.writeFileSync(file, JSON.stringify(say('user', 'first')) + '\n');

const got = [];
const stop = followTranscript(file, (m) => got.push(m.role + ':' + m.text));
assert.deepStrictEqual(got, ['user:first'], 'existing content is read on start');

// A half-written line must not be parsed twice or dropped.
fs.appendFileSync(file, JSON.stringify(say('assistant', 'second')));
setTimeout(() => {
  assert.deepStrictEqual(got, ['user:first'], 'incomplete line is held back');
  fs.appendFileSync(file, '\n' + JSON.stringify(say('user', 'third')) + '\n');
  setTimeout(() => {
    stop();
    assert.deepStrictEqual(got, ['user:first', 'assistant:second', 'user:third'],
      'each message delivered exactly once, in order');
    console.log('transcript: ok');
  }, 1400);
}, 1400);
